### ISSUE TITLE
Thoughts on Anvill?

### ISSUE THREAD

**Issue by pgoodman** [aengelke/rellume#1]
Hello,

Maintainer of McSema, Remill, and Anvill here :-) Your project is very interesting, and we take a similar approach to yours in one of our research projects, [Anvill](https://github.com/lifting-bits/anvill). Anvill  like McSema, uses Remill for instruction semantics, and so we can apply it to 32-bit x86, as well as AArch64 machine code. We've found that using an SROA-based approach, similar to what you do, and inspired by the [SATURN deobfuscator](https://arxiv.org/abs/1909.01752), generates very nice bitcode. What are your thoughts on Anvill, and are you interested in collaboration?

**Comment by pgoodman** [comment]
In many ways, I think our goals are roughly the same: to produce bitcode amenable for analysis/optimization.

Pros:
I would say a design difference between the two is that anvill is guided by a specification, which tells it where to find parameters/return values, whereas rellume hardcodes the sysv/itantium abi. This design difference permits anvill to operate on machine code from different architectures. Anvill supports more instructions by virtue of using Remill, and the instruction semantics are well-tested.

Cons:
Anvill is heavier weight, mostly in terms of it requiring interprocedural optimizations, e.g. inlining of instruction semantics functions. It is early on in its development, and so there are many things that need to be improved.

**Comment by aengelke** [comment]
Hi!

> In many ways, I think our goals are roughly the same: to produce bitcode amenable for analysis/optimization.

Yes.



> I would say a design difference between the two is that anvill is guided by a specification, which tells it where to find parameters/return values, whereas rellume hardcodes the sysv/itantium abi.

This is actually no longer true, Rellume can already handle arbitrary calling conventions. Lifted functions work on a CPU state struct ([specified here](https://github.com/aengelke/rellume/blob/master/data/rellume/cpustruct.json)), and can then be wrapped/modified to any specific calling convention. I'll update the readme to reflect that change, thanks.



> Anvill supports more instructions by virtue of using Remill, and the instruction semantics are well-tested.

True, it takes a lot of time to implement all these instructions. ;)
I currently use Rellume for an LLVM-based dynamic binary instrumenter, so a lot of (non-obfuscated) code (including a plenty of glibc functions) is known to be lifted correctly (and the lifter itself is also quite fast).



> What are your thoughts on Anvill[?]

It's an interesting project to transfer an arbitrary calling convention to some lifted machine code--I was actually thinking of something similar to replace the hard-coded SysV wrapper.



> and are you interested in collaboration?

Sure! What do you have in mind?

**Comment by pgoodman** [comment]
> Lifted functions work on a CPU state struct

Neat, our x86/amd64 state structure is here: https://github.com/lifting-bits/remill/blob/master/remill/Arch/X86/Runtime/State.h

> I currently use Rellume for an LLVM-based dynamic binary instrumenter

For a DBI/DBT use case, Remill is rather slow if it's on your critical path. Whereas you emit bitcode via LLVM APIs directly for each instruction, we emit calls to pre-compiled functions, and rely on optimizations to inline. For background, all of our instruction semantics are written in C++ and compiled into one really large bitcode module. The functions follow a naming scheme that the instruction decoder also follows, allowing us to find semantics functions that correspond to lifted functions. [This](https://github.com/lifting-bits/remill/blob/master/docs/LIFE_OF_AN_INSTRUCTION.md) describes the process in more detail.

> Sure! What do you have in mind?

The crux of it is that I want to know if you'd just switch to working on Anvill :-P I expect the answer is "no" as you've invested a lot into this project, and it appears to be part of your ongoing academic work. Maybe the answer is "yes". Regardless, I think this would be a longer conversation to have over email, perhaps. My email is peter `<at>` trailofbits `<dot>` com.

There are some real challenges that we face with Anvill, and you may have partially for fully solved them, or maybe you face them too (e.g. related to recognizing and re-writing all references to global variables, stack locations, etc.). We can always augment our specifications with more information, especially if the specifications are generated by a commercial disassembly engine such as IDA Pro or Binary Ninja, but that may be "cheating", and also doesn't fit your story.

**Comment by aengelke** [comment]
Continuing discussion via email, closing.
