### ISSUE TITLE
How to use rellume?

### ISSUE THREAD

**Issue by fpb1386** [aengelke/rellume#2]
How to use this tool for binary lifting to IR codes?
I cannot find the content which describe the installation and usage.

**Comment by aengelke** [comment]
You can find a usage example in [examples/lifter.c](https://github.com/aengelke/rellume/blob/cc47757371b81acc9230768e309f9e17a8201671/examples/lifter.c). The installation procedure like any other project that uses meson-build, see the [CI-file](https://github.com/aengelke/rellume/blob/a1bdf0b22f7094b8956ace446d5a0d0748d7713d/.travis.yml#L49-L52) for reference. Closing, as this is not an issue.
