### ISSUE TITLE
Small fixes

### ISSUE THREAD

**Issue by d-ornen** [aengelke/rellume#4]
Project fails to build on my system due to two reasons:
1) I have  llvm 14.0.6 and current meson build config refuses to work with llvm <14. If rellume is strongly bound to llvm version < 14, I suggest adding this information to README.md, otherwise fix the llvm_version variable in topmost meson.build
2) Meson build system refuses to compile project with the following error: 
```examples/meson.build:1:0:` ERROR: No host machine compiler for 'examples/simple-x86-64.c'```.
 Quick googling led me to conclusion that i should fix first line to
 ```project('rellume', ['cpp', 'c'], meson_version: '>=0.49',```
 Attached file contains proposed fixes (.txt part was added due to upload restrictions)
[meson.build.txt](https://github.com/aengelke/rellume/files/9926895/meson.build.txt)

**Comment by aengelke** [comment]
Thanks for pointing this out! Fixed in 7344227 and efcd8a4. Major LLVM version upgrades are always slightly problematic, as there are always API breaks, with some of them being non-trivial to fix (although it was easy this time).
