### ISSUE TITLE
How can I compile rellume? And how can I become a contributor?

### ISSUE THREAD

**Issue by OSPFvX** [aengelke/rellume#5]
hello everyone!
I have some kind of problem with meson(https://stackoverflow.com/questions/75146067/how-can-i-compilegenerate-a-sln-file-or-something-similar-a-project-via-meson?noredirect=1#comment132608738_75146067), it would be great if someone could help me. And it would also be great to find out how i can become a contributor to this project, I could try to help!

**Comment by aengelke** [comment]
Problems with your local setup are not issues with this project. That said, Windows is not supported (the lifter might work, but tests certainly won't) and unlikely to be so any time soon. You can open pull requests.
