### ISSUE TITLE
CreateInsertElement is ambiguous

### ISSUE THREAD

**Issue by UnlimitedChild** [aengelke/rellume#6]
Hello,

I get an error while compiling:

../src/a64/main.cc: In member function 'void rellume::aarch64::Lifter::SetScalar(farmdec::Reg, llvm::Value*)':
../src/a64/main.cc:1032:38: error: call of overloaded 'CreateInsertElement(llvm::Value*&, llvm::Value*&, long unsigned int)' is ambiguous
 1032 |     fullvec = irb.CreateInsertElement(fullvec, val, 0uL);
      |               ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
../src/x86-64/lifter-operand.cc: In member function 'void rellume::x86_64::Lifter::OpStoreVec(rellume::Instr::Op, llvm::Value*, bool, rellume::x86_64::Alignment)':
../src/x86-64/lifter-operand.cc:276:39: error: call of overloaded 'CreateInsertElement(llvm::Value*&, llvm::Value*&, long unsigned int)' is ambiguous
  276 |         full = irb.CreateInsertElement(full, value, 0ul);
      |                ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
../src/x86-64/lifter-sse.cc: In member function 'void rellume::x86_64::Lifter::LiftSseMovScalar(const rellume::Instr&, rellume::Facet)':
../src/x86-64/lifter-sse.cc:126:52: error: call of overloaded 'CreateInsertElement(llvm::Value*&, llvm::Value*&, long unsigned int)' is ambiguous
  126 |         llvm::Value* zext = irb.CreateInsertElement(zero, src, 0ul);

LLVM version 15.0.7, what could be the problem?

 note: candidate: 'llvm::Value* llvm::IRBuilderBase::CreateInsertElement(llvm::Value*, llvm::Value*, llvm::Value*, const llvm::Twine&)'
 2298 |   Value *CreateInsertElement(Value *Vec, Value *NewElt, Value *Idx,

Thanks!

**Comment by aengelke** [comment]
Thanks for finding this. I couldn't reproduce this with Clang or GCC (and LLVM 15.0.7); but pushed 9bb58de which hopefully fixes this. If not, please reopen the issue.

**Comment by UnlimitedChild** [comment]
> Thanks for finding this. I couldn't reproduce this with Clang or GCC (and LLVM 15.0.7); but pushed [9bb58de](https://github.com/aengelke/rellume/commit/9bb58debee8662288a1c0775e454039bc4e0f478) which hopefully fixes this. If not, please reopen the issue.

Compilation completed successfully! Thanks!
